///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:

      - Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

      - Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

      - Neither the name of Oracle nor the names of its
        contributors may be used to endorse or promote products derived
        from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
    IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
    PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
    CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
    EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
    PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
    LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

///////////////////////////////////////////////////////////////////////////////

[WARNING]
*This project is now part of the EE4J initiative. This repository has been archived as all activities are now happening in the https://github.com/eclipse-ee4j/security-examples[corresponding Eclipse repository]. See https://www.eclipse.org/ee4j/status.php[here] for the overall EE4J transition status.*
 
= Examples

The goal if this repo is to get everyone on the same page with level of knowledge.

If you know something, share it!

You don't need to be in the EG to contribute.  Helping raise awareness and educate are critical tasks.

This repo is dedicated to spreading that knowledge and getting us all on the same page.  No assumed knowledge required.

 - https://github.com/javaee-security-spec/bootstrap/tree/master/simple-jaas-example[Simple JAAS Example]
 - https://github.com/javaee-security-spec/bootstrap/tree/master/simple-jaspic-example[Simple JASPIC Example]

The more we collect samples of existing capabilities the better our odds of success.  We can take the good parts, leave the rest and drive commonality across the platform.
